# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.108.0"

default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(
      scheme: "wandr2",
      project: './ios/wandr2.xcodeproj'
    ) # Build your app - more options available
    pilot

    commit_version_bump(
      message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
      xcodeproj: 'ios/wandr2.xcodeproj'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # platform :android do
  #   desc "Deploy a new version to the Google Play Store"
  #   lane :alpha do
  #     gradle(
  #       task: "assemble",
  #       build_type: "Release",
  #       project_dir: "android/"
  #     )
  #     supply(
  #       track: "alpha",
  #       apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
  #     )
  #   end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym(scheme: "wandr2") # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
